import { NextResponse } from "next/server";

export async function POST(req:Request){
 try{
  const {repo,branch="repopilot/approved-change",base="main",files=[],message="chore: apply RepoPilot approved patch",createPr=true,approved=false}=await req.json();
  if(approved!==true) return NextResponse.json({error:"Explicit human approval is required before GitHub writes."},{status:403});
  if(!process.env.GITHUB_TOKEN) return NextResponse.json({error:"GitHub write access is not configured. Add GITHUB_TOKEN server-side before approving changes."},{status:503});
  if(!repo||!Array.isArray(files)||files.length===0) return NextResponse.json({error:"Approval payload is incomplete."},{status:400});
  const h={Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json"};
  const r=await fetch(`https://api.github.com/repos/${repo}/git/ref/heads/${base}`,{headers:h}); if(!r.ok) throw Error("Base branch could not be read.");
  const ref=await r.json();
  const br=await fetch(`https://api.github.com/repos/${repo}/git/refs`,{method:"POST",headers:h,body:JSON.stringify({ref:`refs/heads/${branch}`,sha:ref.object.sha})});
  if(!br.ok) throw Error("Could not create approval branch.");
  for(const f of files){
   const cr=await fetch(`https://api.github.com/repos/${repo}/contents/${f.path}?ref=${encodeURIComponent(branch)}`,{headers:h});
   let sha; if(cr.ok) sha=(await cr.json()).sha;
   const payload:any={message,content:Buffer.from(String(f.content)).toString("base64"),branch}; if(sha) payload.sha=sha;
   const wr=await fetch(`https://api.github.com/repos/${repo}/contents/${f.path}`,{method:"PUT",headers:h,body:JSON.stringify(payload)});
   if(!wr.ok) throw Error(`Could not write ${f.path}.`);
  }
  if(!createPr) return NextResponse.json({branch});
  const pr=await fetch(`https://api.github.com/repos/${repo}/pulls`,{method:"POST",headers:h,body:JSON.stringify({title:message,head:branch,base,body:"Generated by RepoPilot after explicit human approval. Please review before merging."})});
  if(!pr.ok) throw Error("Changes committed, but PR creation failed.");
  const p=await pr.json(); return NextResponse.json({branch,prUrl:p.html_url,prNumber:p.number});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Approved change failed"},{status:500});}
}